import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub,AiFillFacebook, AiFillHtml5 } from 'react-icons/ai';
import {DiCss3,DiReact} from 'react-icons/di';
import {SiJavascript,SiTailwindcss} from 'react-icons/si';
import {FaGitAlt} from 'react-icons/fa';
import {IoLogoNodejs} from 'react-icons/io'
import Image from 'next/image';
import avtar from '../public/avtar.png';
import starbucks from'../public/starbucks.png';
import bot from '../public/bot.png'
import nfc from '../public/nfc.png';
import {SiNfc,SiGmail} from 'react-icons/si';
import thissite from '../public/thissite.png';
import autocare from '../public/autocare.png';
import {BsWordpress} from 'react-icons/bs';
import {useState} from 'react';
import face from '../public/face.png';
import movie from '../public/movie.png';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (

    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bhuwan Aryal Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/1.png" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-7 bg-white flex justify-between dark:bg-gray-900   '>
          <h1 className='text-xl font-burtons font-bold dark:text-white'>Bhuwan Aryal</h1>
          <ul className='flex item-center sticky top-0 dark:text-white'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/file/d/1kG7tnCFy6LVVC9AznsbksBEaaMA2T8KE/view?usp=sharing">Resume</a></li>
          </ul>
         </nav>
         <div className='flex justify-start mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-100 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={avtar}/>
          </div>
         <div className='text-center p-10'>
           <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white'>Bhuwan Aryal</h2>
           <h3 className='text-2xl md:text-3xl dark:text-white'>FrontEnd Developer</h3>
         </div>
         <div className='text-5xl flex justify-center gap-16 text-gray-600 '>
          <a className='text-blue-900 hover:text-gray-600 dark:text-white' href="https://www.linkedin.com/in/bhuwan-aryal-2b77231a2/"><AiFillLinkedin  /></a>
          <a className='text-black hover:text-gray-600 dark:text-white'href="https://github.com/bhuwanaryal0202"><AiFillGithub /> </a>
          <a className='text-blue-900 hover:text-gray-600 dark:text-white' href="https://www.facebook.com/bhuwan.aryal.79"><AiFillFacebook /> </a>   
          <a className='text-red-700 hover:text-gray-600 dark:text-white' href="https://mail.google.com/mail/?view=cm&fs=1&to=bhuwanaryal0202@gmail.com"><SiGmail /> </a>     
         </div> 
         <div className='text-center p-3'>
         <h4 className='text-3xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white '>What I Do</h4>
           <p className='text-xl py-5 leading-8 text-gray-800 dark:text-white'>
              Building Web Apps with Mordern Technologies </p>
              <div className='text-5xl flex justify-center gap-5 py-3 text-black-600'>
                <AiFillHtml5  className='text-orange-600'/>
                <DiCss3 className='text-blue-800' />
                <DiReact className='text-blue-400' />
                <SiJavascript className='text-yellow-500'/>
                <SiTailwindcss className='text-blue-600' />
                <IoLogoNodejs className='text-green-600'/>
                <FaGitAlt  className='text-red-600' />
                </div>
                <div>
                <p className='text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>
                ⚡ Developing scalable and reusable front-end components with React.js. <br />
                ⚡ Developing new user-facing features, determining the structure and design of web pages. <br />
                ⚡ Building reusable codes, optimizing page loading times. <br />
                ⚡ Data handling and API calls to back-end with Node.js. <br />
                </p>
                </div>
         </div>
        </section>
        <section>
          <div className='text-center  p-10'>
           <h3 className='text-4xl  dark:text-white'>Projects</h3> 
          </div>
          <div className=' flex flex-wrap gap-6  '>

          <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white'>
              <Image src={movie} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>Movie Check App</h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      <AiFillHtml5 className='text-orange-600'/>
                      <DiCss3 className='text-blue-800' />
                      <SiJavascript className='text-yellow-500'/>
   
                </div>
                   <br />
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://movie-check-app.netlify.app">Site</a>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/bhuwanaryal0202/Movie_Check_app">Code</a>
            </div>
            <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white'>
              <Image src={starbucks} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>Starbucks Homepage Clone</h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      <AiFillHtml5 className='text-orange-600'/>
                      <DiCss3 className='text-blue-800' />
   
                </div>
                   <br />
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://starbuck-clone-bhuwan.netlify.app/">Site</a>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/bhuwanaryal0202/starbucks_clone">Code</a>
            </div>
            <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white'>
              <Image src={bot} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>Chat Bot</h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      <AiFillHtml5 className='text-orange-600'/>
                      <DiCss3 className='text-blue-800' />
                      <SiJavascript className='text-yellow-500'/>
   
                </div>
                   <br />
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://htmlcssjsonlychatbot.netlify.app">Site</a>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/bhuwanaryal0202/HTML_CSS_JS-ChatBot">Code</a>
            </div>
            <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white' >
              <Image src={nfc} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>NFC Business Card</h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      <AiFillHtml5 className='text-orange-600'/>
                      <DiCss3 className='text-blue-800' />
                      <SiNfc className='text-blue-600 text-medium' />
   
                </div>
                   <br />
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://socialcard-bhuwan-aryal.netlify.app/">Site</a>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/bhuwanaryal0202/bhuwanaryal0202.github.io">Code</a>
            </div>
            <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white' >
              <Image className='shadow-md' src={thissite} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>Portfolio Website</h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      
                      <SiTailwindcss className='text-blue-600' />
                      <SiJavascript className='text-yellow-500'/>
                      <DiReact className='text-blue-400' />
   
                </div>
                   <br />
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/bhuwanaryal0202/my-portfolio-website-code">Code</a>
            </div>
            <div className='text-center  shadow-2xl p-8 rounded-xl my-10 dark:bg-white'>
              <Image src={autocare} width={250} height={200} />
              <h2 className='text-xl font-medium pt-8 pb-2'>E-Commerce Website </h2>
              
                <h4 className='py-4 font-bold text-black'>Tools I use</h4>
                <div className='text-5xl flex justify-center gap-5 py-3 '>
                      <AiFillHtml5 className='text-orange-600'/>
                      <DiCss3 className='text-blue-800' />
                      <BsWordpress className='text-cyan-800' />
   
                </div> 
            </div>
          </div>
          <div className='text-center p-10' >
          <h3 className='text-4xl py-1 dark:text-white'>Reach Out to Me!</h3>
          <div className='flex justify-start mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-100 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={face} />
          </div>
          
          <h3 className='text-2xl md:text-3xl  py-3 dark:text-white'>FrontEnd Developer</h3> <br />
          <h3 className='text-xl md:text-2xl  dark:text-white'>📍 Melbourne, Victoria, Australia</h3>
          <h3 className='text-xl md:text-2xl  dark:text-white'>Open for opportunties: Yes</h3>
          <h3></h3>
          <div className='text-5xl p-10 flex justify-center gap-16 text-gray-600 '>
          <a className='text-blue-900 hover:text-gray-600 dark:text-white' href="https://www.linkedin.com/in/bhuwan-aryal-2b77231a2/"><AiFillLinkedin  /></a>
          <a className='text-black hover:text-gray-600 dark:text-white'href="https://github.com/bhuwanaryal0202"><AiFillGithub /> </a>
          <a className='text-blue-900 hover:text-gray-600 dark:text-white' href="https://www.facebook.com/bhuwan.aryal.79"><AiFillFacebook /> </a>   
          <a className='text-red-700 hover:text-gray-600 dark:text-white' href="https://mail.google.com/mail/?view=cm&fs=1&to=bhuwanaryal0202@gmail.com"><SiGmail /> </a>     
         </div> 
          </div>
        </section>
      </main>
    </div>
  );
}
 